### ISSUE TITLE
Live Component doesn't render conditional element

### ISSUE THREAD

**Issue by gregor-i** [phoenixframework/phoenix_live_view#1265]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 23 [erts-11.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.11.2 (compiled with Erlang/OTP 23)
```
* Phoenix version (mix deps):
```
* phoenix 1.4.16 (Hex package) (mix)
  locked at 1.4.16 (phoenix) 856cc1a0
  ok
```
* Phoenix LiveView version (mix deps): 
```
* phoenix_live_view 0.15.0 (Hex package) (mix)
  locked at 0.15.0 (phoenix_live_view) d42ad9b5
  ok
```
* NodeJS version (node -v): `v12.10.0`
* NPM version (npm -v): `6.10.3`
* Operating system: `Ubuntu 18.04.5 LTS`
* Browsers you attempted to reproduce this bug on (the more the merrier): `Chromium 87.0.4280.66 Built on Ubuntu , running on Ubuntu 18.04`
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: `Yes`

### Reproduce

* clone my fork of `phoenix_live_view_example`: [Fork](https://github.com/gregor-i/phoenix_live_view_example)
* setup and run `mix phx.server`
* open `http://localhost:4000/users-auto-scroll` in your favorite browser
* click on `user 1`

### Actual behavior

* Only the number increases.

### Expected behavior

* The number increases AND the new `tr`-element gets inserted.

### superficial analysis
 * The issue arises if the component has a single element and a second element gets added. If the component initially has 2 elements, it dosn't arise.
 * The issue seems to be with the javascript, as the new element gets send to browser, but it dosn't get patched into the dom.
 * The problem seems to be somewhere before the call to `recursiveMerge(target, source)` as `target` already contains the new `tr`-element.

**Comment by josevalim** [comment]
You are using a relatively old version of LiveView and it is likely this bug has been fixed in more recent versions. Can you please update and report back? Thank you.

**Comment by gregor-i** [comment]
I've upgraded live view in the example repo to 0.15.0 and the issue still exists.

Commit: https://github.com/gregor-i/phoenix_live_view_example/commit/7b73d8232874cd5cfe16d13e5b5591fc44517301

**Comment by chrismccord** [comment]
At first glance, it looks like you are not setting a unique ID on the appended tr's for the count row:

https://github.com/gregor-i/phoenix_live_view_example/blob/7b73d8232874cd5cfe16d13e5b5591fc44517301/lib/demo_web/live/user_live/index_auto_scroll.ex#L37

Can you ensure a unique ID on that tr and report back? The js console should also be warning about the lack of ID. Thanks!

**Comment by gregor-i** [comment]
I've added an unique id to the conditional element: [Commit](https://github.com/gregor-i/phoenix_live_view_example/blob/e6dfb37457eacc355c009e5991dacf76b6452c76/lib/demo_web/live/user_live/index_auto_scroll.ex#L35)

The issue still exists.

**Comment by chrismccord** [comment]
The attribute in your linked commit is `if`, not `id` : )

    <tr if="<%= @id %>-second-row">

**Comment by gregor-i** [comment]
Oh, your right. I've fixed it: [Commit](https://github.com/gregor-i/phoenix_live_view_example/commit/0a90002b83e8a9ba96ca2e49f0bf2d3a089f7d75)

But the issue still exists.

**Comment by dvic** [comment]
I think you're using the same ID twice? Try `second-<%= @id %>` as the id?

**Comment by gregor-i** [comment]
No, the ids are unique. The second `tr` already has an postfix of `-second-row`.

Guys, I took the time to create a reproducible and minimal example. Check it out.

**Comment by chrismccord** [comment]
Minor note:

> Guys, I took the time to create a reproducible and minimal example. Check it out.

I did check this out, on the weekend FYI :) Your initial linked commit contained phx-update=append,  which was later removed, and append based updates require IDs, so it was definitely quickest starting point feedback I could provide before seeing if digging in deeper was necessary. This was indeed a bug, just keep in mind the back-and-forth spot-checks are absolutely part of the process. Thanks for the report!
