### ISSUE TITLE
Mobile Safari SVG Click events not triggering handle_event

### ISSUE THREAD

**Issue by winescout** [phoenixframework/phoenix_live_view#1283]
### Environment

* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps):  1.5.7
* Phoenix LiveView version (mix deps): 0.15.0 and 0.14.7
* NodeJS version (node -v): 15.4.0
* NPM version (npm -v): 7.0.15
* Operating system:  Server: MacOS and Elixir docker container 
* Browsers you attempted to reproduce this bug on (the more the merrier):  Mobile Safari (not working), Mobile Chrome (working)
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

phx-click events are not triggered in mobile Safari.  Tested in Simulator and hardware.  Behaves as expected in Chrome, Safari, and Firefox on Desktop.  Behaves as expected on Mobile Chrome.

Here is an example of non-functioning code:
https://github.com/winescout/phoenix-svg-ios-bug-demo/blob/main/lib/svg_events_on_ios_web/live/svg_live/index.ex

### Expected behavior

Expect same as other browsers

**Comment by chrismccord** [comment]
I believe this is addressed in 0.15.1, but SVG may be a special case. Please try and report back! Thanks!

**Comment by winescout** [comment]
In the murky world of Webpack, I did my best to double check I updated successfully to 0.15.1.  I'm still seeing the issue in Mobile Safari.

Is this line here how this was addressed?  https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view.js#L1002

` document.body.addEventListener("click", function(){}) `

I'll do some poking around and see if I can get more information here.

**Comment by winescout** [comment]
I figured out what was going on here, and a work around.  Mobile Safari does not fire a click event on "non-clickable" elements.  SVG polygons, and probably the rest of the shapes is/are non-clickable.  So, no soup and no click event for me.

Fortunately, there is a workaround.  SVG has its own version of the <a> tag that works exactly like the vanilla <a> tag, and that does fire click events inside of an SVG.  So, the code linked above is made working like this:

`
  @impl true
  def render(assigns) do
    ~L"""
    <h1>SVG Click Demo of IOS bug.</h1>

    <p>This works fine in the browser, but click (press) events are not triggered on IOS.  Tested against simulator, and hardware</p>

    <svg height="250" width="500">
      <a href="#" phx-click="click_happened">
        <polygon
          points="220,10 300,210 170,250 123,234"
          style="fill:<%= @color %>;stroke:purple;stroke-width:1"
        />
      </a>
    </svg>
    """
  end
`

Now, one side note to the 'fix' above.  When I was poking at this, I did get events to trigger by adding a bindClick for "touchend" in the bind clicks section of phoenix_live_view.js  around 1098, like so:

`
  bindClicks(){
    this.bindClick("click", "click", false)
    this.bindClick("touchend", "click", false)
    this.bindClick("mousedown", "capture-click", true)
  }
`

Hope that was helpful.

**Comment by semmel** [comment]
> Not a bug, but one of Mobile Safari's many eccentricities it turns out.
> 
> Divs and all non clickable elements behave the same way. Mobile Safari does not fire a click event on "non-clickable" elements. SVG polygons, and probably the rest of the shapes is/are non-clickable. …

Just a short note: That behaviour seems to have changed; Now in Mobile Safari 16 SVGs are "clickable".

Btw. nice trick inserting a "blind" `<a>` tag into the SVG!  Though for older Mobile Safari I wrap my SVGs simply with `<button>`. (entirely unrelated to this project here)
