### ISSUE TITLE
Select prompt 

### ISSUE THREAD

**Issue by tomciopp** [phoenixframework/phoenix_live_view#160]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.3
* NodeJS version (node -v): 11.3.0
* NPM version (npm -v): 6.9.0
* Operating system: Mac OSX 10.14.4 (18E226)

### Actual behavior

<select></select> prompt is discarded when live view is mounted. Form is rendered correctly with "Please Select" prompt which then disappears once the connection back to the server is made.

### Expected behavior

Prompt messages should remain visible until a value is selected.

**Comment by snewcomer** [comment]
@tomciopp Do you have screenshots or code to share? This might be something I can help with.

**Comment by chrismccord** [comment]
@tomciopp please provide more info, and your LiveView module/template so we can assess what the issue may be. The LiveView container itself is disable and put into a loading state with css so the page shouldn't be interactive until connection. It's not clear from the description what the issue is so we need more info to help. Thanks!

**Comment by alexgaribay** [comment]
@chrismccord I can confirm this behavior. The default value will be selected when no value is supplied. As soon as `socket.connect()` is invoked, the default clears. I'll whip up an example.

**Comment by snewcomer** [comment]
@alexgaribay @tomciopp Is the default attr on the option `selected="selected">` or just `selected>`? If the former, I think I can fix!

**Comment by snewcomer** [comment]
I'm assuming this is in morphdom b/c i don't see anything with selects here.  Although I'm not able to reproduce with tests, so will need some information from that example! 🙇

**Comment by tomciopp** [comment]
@chrismccord @snewcomer I'll put together a repo that demonstrates the issue so you all can have more context.

**Comment by alexgaribay** [comment]
You can view the bug in https://github.com/alexgaribay/select.

**Comment by snewcomer** [comment]
@alexgaribay @tomciopp Took a quick peek.  Something like this should work - removing `prompt` and putting it in the list of options + `selected: <value>`.

```
<%= select(f, :value, [[key: "Select an Option", value: 0], "Option 1": "1", "Option 2": "2", "Option 3": "3"], selected: 0, style: "width: 40rem") %>
```

**Comment by alexgaribay** [comment]
Although that may be a work around, it seems less than ideal since it breaks existing Phoenix.HTML functionality.

**Comment by snewcomer** [comment]
So in the HTML spec, there is a concept of "form reset".

`The reset algorithm for select elements is to go through all the option elements in the element's list of options, set their selectedness to true if the option element has a selected attribute, and false otherwise, set their dirtiness to false, and then have the option elements ask for a reset.`

I'm not sure if that is what is exactly going on but I imagine the html spit out by Phoenix.HTML is still semantically correct HTML.  What exactly "breaks"?  Perhaps you need to add the `disabled: true` attribute to the prompt key value list so it can't be selected as well??

The important thing is the "Select an Option" is still the first option element after the diff.  There are things that are happening behind the scenes in the browser (form reset algorithm perhaps) that are causing this.  I imagine it is this:

```
document.querySelector('form select').selectedIndex = -1;
```

**Comment by snewcomer** [comment]
One further question - in morphdom, we could always set the `selectedIndex = 0` by default.  Is there ever a use case where it should be -1 and just show an empty block?  I don't think so, which in that case will be an easy fix.  What do ya'll think?

**Comment by DavidVII** [comment]
I came across this issue just a few days ago and can confirm the behavior described. I made a post about it in the [ElixirForums](https://elixirforum.com/t/phoenix-liveview-has-odd-behavior-with-select-tags).

I was able to get around the initial issue of the prompt option not being selected by removing it and setting the value:

```
<%= select f, :template_id,
    [{"Custom", nil}] ++ Enum.map(@templates, &{&1.name, &1.id}),
    value: (if @current_template, do: @current_template.id, else: nil)
%>
```

Unfortunately, this results in other issues. After any changeset updates (say after submitting the form), I'm unable to select the custom/nil option. Choosing an option with a value appears to work just fine.

Here's a gif of what happens. Notice the behavior after validation error:

![error](https://d1czrtm2mp3lak.cloudfront.net/items/3Z3a3v0f3a0d2f0e1X3H/Screen%20Recording%202019-04-06%20at%2004.29%20PM.gif)

I tried replacing the `value` option from the select tag and setting the `selected` option instead, and it makes matters worse somehow:

![error](https://d1czrtm2mp3lak.cloudfront.net/items/2U3Z012p3m0z0Z2t2F0W/Screen%20Recording%202019-04-06%20at%2004.46%20PM.gif)

It seems that whatever is set in the changeset is what the select tag picks, even if I set the value manually as I do above.

All this might be due to it being a LiveView, so perhaps we have to approach things differently? Of course, everything works as expected outside of a LiveView.

**Comment by snewcomer** [comment]
@DavidVII Seems like your issue is a bit different that described above which dealt with a lack of a `selected` option.  It is hard to tell if yours has to do with HTML or changeset/data handling.  

If you had screenshots of the actual HTML at different states (e.g. select after validation, etc) that would help.  A reproduction would be super as well.

**Comment by DavidVII** [comment]
Thanks for responding, @snewcomer! Indeed this might warrant a separate issue. The way I got here was by trying to address the issue reported here by @tomciopp.

Before Submitting (no changeset errors)
<img width="601" alt="Before submit" src="https://user-images.githubusercontent.com/504075/55984913-6d75fa00-5c53-11e9-884d-b1e07f6d46d7.png">

After Submitting (changeset errors)
<img width="603" alt="After Submit" src="https://user-images.githubusercontent.com/504075/55984955-81b9f700-5c53-11e9-959d-518f1d6d5a77.png">

After changing the select to "Custom" 
<img width="599" alt="After selecting Custom option" src="https://user-images.githubusercontent.com/504075/55985006-9e562f00-5c53-11e9-973c-86854f91d261.png">

Looks like it's not unselecting the original value. If I update the `select_tag` with a prompt, and selected option, I get the same behavior:

```
<%= select f, :template_id,
    Enum.map(@templates, &{&1.name, &1.id}),
    prompt: "Custom",
    selected: (if @current_template, do: @current_template.id, else: nil),
%>
```

Interestingly enough, it seems like the markup is updating just fine, but as soon as I make a change to a field (to address validation issue), the form rerenders and uses the changeset to set the value on that select tag. Check it out: https://cl.ly/e7fc75320d69

Here's my `phx_update` handler:

```
def handle_event("change", %{"credential" => params}, socket) do
  case params["template_id"] do
    "" ->
      {:noreply, assign(socket, current_template: nil)}

    string_id ->
      template = get_template(string_id)
      {:noreply, assign(socket, current_template: template)}
  end
end
```

While I feel that this is related, please let me know if you think I should open up another issue. Thanks!

**Comment by snewcomer** [comment]
In [morphdom](https://github.com/patrick-steele-idem/morphdom/blob/master/src/specialElHandlers.js#L93), once we detect a "selected" option, we break out of the loop.  It shouldn't add the `selected` attribute to multiple options.  Also, since your html looks correct after the server response (the only time morphdom/live_view deals with the HTML), it seems to either do with the logic or something in Phoenix HTML.  Nothing is touching the websocket with "After changing the select to "Custom", right? 

I put up a PR that may contain a fix [here](https://github.com/phoenixframework/phoenix_live_view/pull/178) but not sure it is applicable to this case..

**Comment by DavidVII** [comment]
Thanks, @snewcomer! I'm curious to see if that fixes the issue.

> Nothing is touching the websocket with "After changing the select to "Custom", right?

The `handle_event` _does_ in fact update the socket. My example above shows more detail, but I'm responding with a `{:noreply, assign(socket, current_template: template}`

**Comment by chrismccord** [comment]
Fixed via #178

**Comment by DavidVII** [comment]
@chrismccord @snewcomer, unfortunately, this did not fix the issue I've been seeing (described [here](https://github.com/phoenixframework/phoenix_live_view/issues/160#issuecomment-482242407)).

I've decided to put together a tiny app that demonstrates the issues here:

https://github.com/DavidVII/liveview-issues

I've included steps that you can take to reproduce the issues I'm having in the README.

What I'm trying to do is update the view based on the currently selected option in the form. Perhaps I'm doing something wrong, but I imagine this might be a common use case for Phoenix LiveView.

Take a look at the LiveView module:
https://github.com/DavidVII/liveview-issues/blob/master/lib/select_web/live/page_live/index.ex

The README should make it easy to reproduce the issues, but of course, I'm happy to go into any further details.

I'm a HUGE fan of LiveView and am even using it in production. Thanks for all the work and effort 😊

**Comment by DavidVII** [comment]
Hi, just wanted to follow up on the select tag issue. ☝️

Has anyone had a chance to see the example I put together demonstrating the issue?

**Comment by jmilamwalters** [comment]
I am experiencing the issue documented by @DavidVII [here](https://github.com/DavidVII/liveview-issues#2-nil-option-is-not-selected-after-form-is-submitted) as well.

**Comment by snewcomer** [comment]
@DavidVII Looking at the issue 👁.  Overall, this might be an issue in the diffing from us.  A couple of other notes that could be considered workarounds.

This seems to be one place - https://github.com/DavidVII/liveview-issues/blob/master/lib/select_web/live/page_live/index.ex#L36.  You lose the `selected` value b/c `current_type` gets unset.  If you change the `types` to a list keyed by only integers, everything works as expected.  So `nil` as the `option` value is the issue.

Another side note, I wasn't sure if you wanted to persist the changes in the changeset from `handle_event`, this gets it working as well.

```ex
    changeset = Select.Identity.change_user(%Select.Identity.User{}, params)
```

Otherwise, I'll look into a fix for the diffing in the meantime.

**Comment by snewcomer** [comment]
Also, just to follow up, the diffing does not turn out to be the issue. Once you submit your form, the changeset has a value of `nil` for the `type` and isn't able to recover.  Because `nil` is a potential value and the `changeset` isn't being updated on `change`, Phoenix doesn't know how to `render` your select tag.
