### ISSUE TITLE
LiveView seems to ignore data confirm

### ISSUE THREAD

**Issue by DavidVII** [phoenixframework/phoenix_live_view#235]
### Environment

* Elixir version (elixir -v): 1.8.1
* Phoenix version (mix deps): 1.4.
* NodeJS version (node -v): v10.15.3
* NPM version (npm -v): Using yarn version: 1.16.0
* Operating system: MacOS 10.14.5

### Actual behavior

LiveView event is triggered despite using `data: [confirm: "Are you sure?"]` on the element.

Clicking on a delete link that triggers an event that also has a data confirm added to it ignores the data confirm and executes the event regardless of what the user chooses.

```
<%= link "Delete", to: "#",
    phx_click: :remove_todo,
    phx_value: todo.id,
    data: [confirm: "Are you sure you want to delete this todo?"] %>
```
### Expected behavior

The event should not be triggered unless the user chooses to confirm the request.

I have the latest versions of LiveView and `phoenix_html` installed.

**Comment by DavidVII** [comment]
Oh jeez... Of course, the second after I created this I decided to double check and make sure I had the refreshed js libs. My bad. Issues seem to have been resolved in the latest update of `phoenix_html`. I am closing this issue.

**Comment by edisonywh** [comment]
Did you just run `npm install --force phoenix_html` to refresh it? I did the same but it's still happening for me. In my case, the data prompt does not even show up at all, it just executes instantly.
