### ISSUE TITLE
no case clause matching: %Phoenix.LiveView.Route after connection lost

### ISSUE THREAD

**Issue by dfalling** [phoenixframework/phoenix_live_view#2518]
### Environment

* Elixir version (elixir -v): `1.14.3`
* Phoenix version (mix deps): `1.7.1`
* Phoenix LiveView version (mix deps): `0.18.17`
* Operating system: `MacOS Ventura 13.0`
* Browsers you attempted to reproduce this bug on (the more the merrier): `Firefox`, `Chrome`, `Safari`
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: `yes`

### Actual behavior

In Firefox, LiveView sometimes has a case match error when reconnecting after lost network or updated server deploy.

```elixir
channel.ex 1001 verified_mount/8
lib/phoenix_live_view/channel.ex:1001:in `verified_mount/8’ 5

no case clause matching: %Phoenix.LiveView.Route
{
  path: ["trips", "73aa7d4c-1324-4acb-8724-1c0c04c56153"],
  view: IdoWeb.TripLive.Show, action: :show,
  opts: [action: :show, router: IdoWeb.Router],
  live_session: %{extra: %{on_mount: [%{function: &IdoWeb.UserAuth.on_mount/4,
    id: {IdoWeb.UserAuth, :ensure_authenticated}, stage: :mount}]},
  name: :require_authenticated_user, vsn: 1674007287466869182},
  params: %{"id" => "73aa7d4c-1324-4acb-8724-1c0c04c56153"},
  uri: %URI{scheme: nil, userinfo: nil, host: nil, port: nil,
  path: "/trips/73aa7d4c-1324-4acb-8724-1c0c04c56153", query: nil, fragment: nil}
}
```

In my app this happens consistently on my `trips/id/show/edit` route but rarely if another route is active.

Best steps to reproduce:
- navigate to the edit screen
- toggle Firefox into "Work Offline" mode (or toggle off your computer's internet) (note this only works for remote servers, not localhost)
- Firefox will immediately show the "we're trying to reconnect" modal
- Reconnect your network
- LiveView crashes and reloads

### Expected behavior
- I think the "we're trying to connect" modal probably shouldn't even show yet? It doesn't in Chrome or Safari
- The browser should reconnect flawlessly without the crash

I know this isn't a ton to go on- if this isn't reproducible in existing projects, I can try to bootstrap a new one.

**Comment by begedin** [comment]
Had a look but was not able to reproduce. It looks like firefox offline mode actually lets localhost requests through, so you'd have to run it against a deployed app or via some loopback to get it to work.

I think this would be the code that triggers the issue.

```Elixir
{params, host_uri, action} =
  case route do
    %Route{uri: %URI{host: host}} = route when byte_size(host) <= @max_host_size ->
      {route.params, route.uri, route.action}

    nil ->
      {@not_mounted_at_router, @not_mounted_at_router, nil}
  end
```

I assume the problem is with `%URI{}` fields being `nil`.

This value is coming from `Route.live_link_info`, the clause where url is passed in as string, and is then parsed using `URI.parse`, to become this. So the original url string gets wrong somehow, somewhere.

Not an answer, but might potentially help someone else.

**Comment by dfalling** [comment]
Thanks for digging into this @begedin! I'll try to bootstrap a sample project to illustrate the issue. It reliably fails on my app but I'm worried I'll be error free on a clean project.

**Comment by dfalling** [comment]
@woylie have you noticed if it happens after a redeploy? That's my most common scenario if I'm not deliberately trying to trigger it with one one problematic view.

**Comment by dfalling** [comment]
Okay, I've finally narrowed it down quite a bit and have a lean sample app to demonstrate the issue

### Steps to reproduce
- navigate to detail route via `{JS.patch(~p"/widgets/#{@widget}/show/edit")}`
- toggle Firefox's "Work Offline" to go offline
- wait a few seconds
- toggle Firefox's "Work Offline" to reconnect

If I navigate to the exact same route via a `<.link patch={~p"/widgets/#{@widget}/show/edit"}>Edit</.link>` it won't crash.

This fails 100% of the time for me in Firefox. It will occasionally fail in Safari/Chromium-based browsers, but is much more rare.


### Sample app
Created via
- `phx.new`
- `phx.gen.auth Accounts User users`
- `mix phx.gen.live Store Widget widgets name:string`
- Added button to patch edit view:
```
    <button phx-click={JS.patch(~p"/widgets/#{@widget}/show/edit")} class="rounded bg-slate-200"> Edit widget
    </button>
```

- [Github](https://github.com/dfalling/liveview-crash)
- [live demo](https://crashety-live-crash.fly.dev/widgets/1)
  - username: `dummy@example.com`
  - password: `N7VuUDY2ov3rxn`

**Comment by dougw-bc** [comment]
I have noticed this behaviour, also immediately after a redeploy.  It seems to happen on edit/form pages in particular.
Might have something to do with form recovery...

**Comment by darrenklein** [comment]
Just noting that I've been seeing this intermittently as well - haven't been able to associate with deployments/form state/`JS.patch` yet.

**Comment by ethangreenberg** [comment]
I've been getting this error by
1. Clicking on a button/link that does a `JS.patch`
2. Disconnect and reconnecting the server by running `liveSocket.disconnect(); setTimeout(() => liveSocket.connect(), 500)` on the console

**Comment by dfalling** [comment]
I just retested this with the latest versions of Phoenix (1.7.3) and LiveView (0.19.3) and it still happens. I was hoping the recent socket fixes would have addressed this but no luck.

**Comment by SteffenDE** [comment]
Seeing this issue as well in our monitoring.

**Comment by bigardone** [comment]
👋🏼 Same issue here using Chrome, and simply stopping & starting Phoenix's server on my dev env. When the current LC tries to reconnect, it throws the error.

**Comment by petelacey** [comment]
If it helps at this late stage, here's another "me too" for this issue. I can confirm that it 1. happens reliably after a deploy, but also at other (inconsistent) times, and 2. is related to `push_patch`.

**Comment by chrismccord** [comment]
This should be fixed on main. thanks!

**Comment by AndroidOatmeal** [comment]
Anyone else still experiencing this issue? Our app is constantly (and randomly) reporting strange pattern match errors like this:

```elixir
FunctionClauseError: ** (FunctionClauseError) no function clause matching in Web.FooBar.AddLive.handle_event/3
lib/web/live/foo_bar/add_live.ex:34 in Web.FooBar.AddLive.handle_event("...", %{"..." => %{"..." => "..."}}, %Phoenix.LiveView.Socket{...})
```

This happens on a variety of routes. As far as I can tell, there is no legitimate way for this pattern match to fail — these missing params are required at the router level.

**Comment by dfalling** [comment]
I haven't had any issues since the fix in October. Your issue sounds different- it's happening in `handle_event` in your LiveView instead of LiveView's channel.

**Comment by bigardone** [comment]
We are still experiencing this issue too :(

**Comment by josevalim** [comment]
Unless there is a way to reproduce this, we can't help much. Also, for people adding comments, **please include your LiveView version**.

**Comment by Malian** [comment]
I was able to reproduce this bug when I was trying to use `JS.patch` instead of `JS.navigate`. I'll try to isolate the bug into a minimum application, but in the meantime I posted this comment so if anyone has an idea, it might save some time.
