### ISSUE TITLE
Possible race condition causing some elements to be skipped on a re-render?

### ISSUE THREAD

**Issue by sevenseacat** [phoenixframework/phoenix_live_view#3169]
### Environment

* Elixir version (elixir -v): Elixir 1.15.4 (compiled with Erlang/OTP 26)
* Phoenix version (mix deps): phoenix 1.7.11
* Phoenix LiveView version (mix deps): phoenix_live_view 0.20.12
* Operating system: MacOS Sonoma 14.2.1
* Browsers you attempted to reproduce this bug on (the more the merrier): Fifox 123.0.1, Safari 17.2.1, Chrome 122.0.6261.112
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Reproduction single-file app: https://gist.github.com/sevenseacat/4671309ec6352b6abe9b4d7b1c2657bb

This could probably be made a lot simpler but then the behaviour gets intermittent - this seems to be the combination of things that reliably triggers the behaviour.

Run the app and press one of the three buttons to load a form for that record. Then press a different button, and some of the form elements disappear (in the nested FormColumn component). Pressing different buttons won't make them reappear.

### Expected behavior

The FormColumn form fields should be re-rendered when switching between forms for different records.

#### Things that make the behaviour more correct but still not 100% reliable

* Changing the loading of data to be inline instead of async
* Changing the loading of data to use LV's `assign_async`
* Removing dynamic identifiers from the live components `id` attributes, eg. taking the record reference out of `<.live_component module={Example.FormColumn} id={"column-#{@record["id"]}"}`
* Adding IDs to the root-level elements of the components that get skipped

Originally I thought this was related to #3026 but now I'm not so sure, as it can be reliably triggered without nested form fields.

**Comment by chrismccord** [comment]
Thank you for the reproduction! This has been fixed and released with 0.20.13

**Comment by sevenseacat** [comment]
Thanks for the super-quick resolution! I'm still seeing some missing elements so I suspect another related edge case needs to be addressed - I'll try to isolate it again and open another issue :)

**Comment by chrismccord** [comment]
Please let me know if you're able to isolate. Thanks!
