### ISSUE TITLE
1.0 Formatter can fail to format fully

### ISSUE THREAD

**Issue by elliottneilclark** [phoenixframework/phoenix_live_view#3555]
### Environment

* Elixir version (elixir -v): Elixir 1.17.3 (compiled with Erlang/OTP 27)
* Phoenix version (mix deps): 1.7.17
* Phoenix LiveView version (mix deps): 1.0.0
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

We are upgrading from previous LV's to 1.0. We had a component that looked like this before formatting:

```
  def h1(%{} = assigns) do
    ~H"""
    <h1 class={[@base_class, @class]} {@rest}>
      <%= render_slot(@inner_block) %><span class={@sep_class}>::<span class={@sub_header_class}><%= render_slot(@sub_header) %></span></span>
    </h1>
    """
  end
```

After formatting, we get this:

```
  def h1(%{} = assigns) do
    ~H"""
    <h1 class={[@base_class, @class]} {@rest}>
      {render_slot(@inner_block)}<span class={@sep_class}>::<span class={@sub_header_class}><%= render_slot(@sub_header) %></span></span>
    </h1>
    """
  end
```

However, running `mix format --check-formatted` will fail with an error since there is still old `<%=` code in the file. Even removing the `<%=` isn't enough; manual formatting is required to get that file to work. You can see the error on this commit: https://github.com/batteries-included/batteries-included/pull/1306/commits/56479a66d4c863762d01088637cdafe1f0d389ba
The manual fix commit is here: https://github.com/batteries-included/batteries-included/pull/1306/commits/c5f273ed0f1267af7a6f028e13ee1ac97c7e47c6

### Expected behavior

`mix format --check-formatted` will always succeed after a successful `mix format`

**Comment by SteffenDE** [comment]
@josevalim this is probably easy for you to fix

**Comment by josevalim** [comment]
This has been fixed in main already. Because there is no space between the tags, the formatter is in preserve mode, and it doesn't change the contents. Main fixed so it doesn't mark --check-formatted as failing.

**Comment by elliottneilclark** [comment]
While master doesn't complain about the formatting, it still fails to fully migrate the format of the example.


```
  def h1(%{} = assigns) do
    ~H"""
    <h1 class={[@base_class, @class]} {@rest}>
      {render_slot(@inner_block)}<span class={@sep_class}>::<span class={@sub_header_class}><%= render_slot(@sub_header) %></span></span>
    </h1>
    """
  end
  ```

**Comment by SteffenDE** [comment]
Can confirm that this still happens in main. Another weird example:

```elixir
def h1(%{} = assigns) do
    ~H"""
    <h1 class={[@base_class, @class]} {@rest}>
      {render_slot(@inner_block)}
      <span class={@sep_class}>
        ::<span class={@sub_header_class}>




          <%= render_slot(@sub_header) %>
    </span>
      </span>
    </h1>
    """
  end
```

which won't be formatted any further, but I don't know why.

**Comment by josevalim** [comment]
This is what I mentioned before: when the formatter sees no space between text and tags, it enters a "preserve" mode, because we assume the user is writing whitespace sensitive code. Adding whitespace there would break actual rendering today. I am not sure there is a general solution to the problem. Perhaps we could change the compiler to still rewrite EEx to curly but keep everything else as is, but that would require introducing a "third" mode to it.

**Comment by SteffenDE** [comment]
aaah I see now, so in that case I'd say it works as expected, but we should probably document this behavior somewhere. Sorry for the noise!
