### ISSUE TITLE
this.el.focus() in the mounted and updated hook functions will produce no result

### ISSUE THREAD

**Issue by DaTrader** [phoenixframework/phoenix_live_view#619]
### Environment

* Elixir version (elixir -v): 1.9.4
* Phoenix version (mix deps): 1.14.12
* Phoenix LiveView version (mix deps): 0.5.2
* NodeJS version (node -v): 12.14.1
* NPM version (npm -v): 6.13.4
* Operating system: Linux Mint

### Actual behavior

A Javascript call to move focus to any element whatsoever in the "updated" and "mounted" functions of a hook will produce no results as after LV finishes rendering it will have the focus move back to the element where it was before the rendering.

The problem persists in v0.5.2 while the behavior is perfectly correct in v0.4.1.

The following will not have the focus moved to a newly added element:
Hooks.MoveFocus = {
  mounted: function() {
    this.el.focus()
  }
};

### Expected behavior

When the mounted or updated events get triggered and the hook functions are invoked, once moved to a desired element, the focus should stay there. (just like it does in v0.4.1)

**Comment by snewcomer** [comment]
👋 Possible to provide a sample repo?  We could get down to the bottom of it pretty quickly.

**Comment by chrismccord** [comment]
We need more information, but you should also try master as several bugs have been fixed in 0.6, as well as master. I just tested, and this works as expected on master. Thanks!

**Comment by DaTrader** [comment]
Just tested on 0.6.0 (not the master, but "~> 0.6.0") and the focus still does not move to the desired element (stays/gets reverted back to on the element where it was before rendering despite the JS code actually moving it).

As for the version on master, I can't start my application when I upgrade to that for it throws exception re handle_params and I can't try to adjust that to your version on master now as the code is extensively relying on params (the session state was not available prior to 0.5.0 and I needed to communicate somehow the changes done by LiveView so I used params heavily).

I'll wait for a stable 0.6.x version and maybe retry then. 

@snewcomer I don't have a sample repo. Would have to construct it from the scratch as I am working on a web application. If you want to reproduce the bug, try rendering a table or something that inserts a new element (say, on a LiveView key event as in my case) and then have your JS hook code either catch that particular element's mounted event or its parent container's updated event. In either case the JS will change the active element (tested by printing the activeElement.id to console within the hook function), but the focus will not move (it will be reverted back to where it was before the element insertion).

So far, the last version that does not have this bug is 0.4.1. Again, I don't know about the master as I cannot use it.

**Comment by DaTrader** [comment]
@chrismccord @snewcomer 

Guys, I've upgraded to 0.7.1 and the bug is still there. I've made a separate demo project repo today for you to see it plain and clear:
https://github.com/DaTrader/elixir_tests/

The code in master is configured for LV 0.7.1 where the JS hook focus upon inserting a row does not work properly. The hook in question is updated, but it doesn't work with the mounted hook either.

The version in the lv_0.4.1 branch work fine.

The procedure is as usual for both versions (make sure you delete build and deps dirs and the mix.lock file):
mix deps.get
cd assets
npm install

When the app starts go to:
localhost:4000/customers

Click on any row and press the Insert key. On 0.4.1 it will properly position the focus where it's told to. On 0.7.1 the focus will remain where it was before the new row was inserted.

I'd like you to reopen the issue and I hope you solve this one quickly.

Thanks

**Comment by chrismccord** [comment]
We restore focus after patch so what you are seeing is the hook is firing properly, but we restore the focus to where you were before patch. The easiest solution for you is to focus on the next event loop after patch is complete, ie from your hook code:

```diff
function move_focus( el)  {
  console.info( "move_focus:", el.id);
- el.focus()
+ setTimeout(() => el.focus(), 0)
  console.info( document.activeElement.id);
}
```

**Comment by chrismccord** [comment]
I have also updated master to apply the updated hooks after focus has been restored

**Comment by DaTrader** [comment]
Thanks. Please make sure to apply the mounted hooks as well for they have the same problem.
